<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>sample page</title>
<script src="js/jquery.1.9.1.min.js"></script>
</head>
<body>
	<h3>hello world!!!</h3>
	<button id="message">send to serve</button>
	<script>
	
	var nodes=[
	           {
	             "group":1,
	             "nodeId":"11",
	             "name":"AgNatRes"
	           },
	           {
	             "group":1,
	             "nodeId":"21",
	             "name":"Oil+"
	           },
	           {
	             "group":1,
	             "nodeId":"22",
	             "name":"Util"
	           },
	           {
	             "group":1,
	             "nodeId":"23",
	             "name":"Const"
	           },
	           {
	             "group":1,
	             "nodeId":"31",
	             "name":"ManEdible"
	           },
	           {
	             "group":1,
	             "nodeId":"32",
	             "name":"ManChem"
	           },
	           {
	             "group":1,
	             "nodeId":"33",
	             "name":"ManElect"
	           },
	           {
	             "group":1,
	             "nodeId":"42",
	             "name":"WholTr"
	           },
	           {
	             "group":1,
	             "nodeId":"44",
	             "name":"Retail"
	           },
	           {
	             "group":1,
	             "nodeId":"45",
	             "name":"Retail"
	           },
	           {
	             "group":1,
	             "nodeId":"48",
	             "name":"Transport"
	           },
	           {
	             "group":1,
	             "nodeId":"49",
	             "name":"Transport"
	           },
	           {
	             "group":1,
	             "nodeId":"51",
	             "name":"Inf"
	           },
	           {
	             "group":1,
	             "nodeId":"52",
	             "name":"FinIns"
	           },
	           {
	             "group":1,
	             "nodeId":"53",
	             "name":"RealEst"
	           },
	           {
	             "group":1,
	             "nodeId":"54",
	             "name":"ProfServ"
	           },
	           {
	             "group":1,
	             "nodeId":"55",
	             "name":"Mgmt"
	           },
	           {
	             "group":1,
	             "nodeId":"56",
	             "name":"Admin"
	           },
	           {
	             "group":1,
	             "nodeId":"61",
	             "name":"Ed"
	           },
	           {
	             "group":1,
	             "nodeId":"62",
	             "name":"HealthSoc"
	           },
	           {
	             "group":1,
	             "nodeId":"67",
	             "name":"U"
	           },
	           {
	             "group":1,
	             "nodeId":"71",
	             "name":"R&R"
	           },
	           {
	             "group":1,
	             "nodeId":"72",
	             "name":"Travel"
	           },
	           {
	             "group":1,
	             "nodeId":"81",
	             "name":"ServOther"
	           },
	           {
	             "group":1,
	             "nodeId":"92",
	             "name":"PubAdmin"
	           },
	           {
	             "group":1,
	             "nodeId":"NA",
	             "name":"NA"
	           },
	           {
	             "group":2,
	             "nodeId":"11",
	             "name":"AgNatRes"
	           },
	           {
	             "group":2,
	             "nodeId":"21",
	             "name":"Oil+"
	           },
	           {
	             "group":2,
	             "nodeId":"22",
	             "name":"Util"
	           },
	           {
	             "group":2,
	             "nodeId":"23",
	             "name":"Const"
	           },
	           {
	             "group":2,
	             "nodeId":"31",
	             "name":"ManEdible"
	           },
	           {
	             "group":2,
	             "nodeId":"32",
	             "name":"ManChem"
	           },
	           {
	             "group":2,
	             "nodeId":"33",
	             "name":"ManElect"
	           },
	           {
	             "group":2,
	             "nodeId":"42",
	             "name":"WholTr"
	           },
	           {
	             "group":2,
	             "nodeId":"44",
	             "name":"Retail"
	           },
	           {
	             "group":2,
	             "nodeId":"45",
	             "name":"Retail"
	           },
	           {
	             "group":2,
	             "nodeId":"48",
	             "name":"Transport"
	           },
	           {
	             "group":2,
	             "nodeId":"49",
	             "name":"Transport"
	           },
	           {
	             "group":2,
	             "nodeId":"51",
	             "name":"Inf"
	           },
	           {
	             "group":2,
	             "nodeId":"52",
	             "name":"FinIns"
	           },
	           {
	             "group":2,
	             "nodeId":"53",
	             "name":"RealEst"
	           },
	           {
	             "group":2,
	             "nodeId":"54",
	             "name":"ProfServ"
	           },
	           {
	             "group":2,
	             "nodeId":"55",
	             "name":"Mgmt"
	           },
	           {
	             "group":2,
	             "nodeId":"56",
	             "name":"Admin"
	           },
	           {
	             "group":2,
	             "nodeId":"61",
	             "name":"Ed"
	           },
	           {
	             "group":2,
	             "nodeId":"62",
	             "name":"HealthSoc"
	           },
	           {
	             "group":2,
	             "nodeId":"67",
	             "name":"U"
	           },
	           {
	             "group":2,
	             "nodeId":"71",
	             "name":"R&R"
	           },
	           {
	             "group":2,
	             "nodeId":"72",
	             "name":"Travel"
	           },
	           {
	             "group":2,
	             "nodeId":"81",
	             "name":"ServOther"
	           },
	           {
	             "group":2,
	             "nodeId":"92",
	             "name":"PubAdmin"
	           },
	           {
	             "group":2,
	             "nodeId":"NA",
	             "name":"NA"
	           }
	         ];
	          

	
		$('#message').click(function(){
			
			var obj=new Object();
			
			$.ajax({
				  type: 'GET',
				  url: 'http://localhost:8080/visualizer/json/node.json',
				  dataType: 'json',
				  success: function(data) { obj.node = data;},
				  error: function(data,error){alert(error);},
				  async: false
				});
			
			alert(JSON.stringify(obj.node));
		});
	</script>
</body>
</html>